FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore --runtime linux-x64
RUN dotnet publish UI/MTWireGuard.csproj \
    -c Release \
    -o /app/publish \
    --runtime linux-x64 \
    --self-contained true \
    /p:WarningLevel=0 \
    /p:PublishTrimmed=false

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/runtime:8.0-bookworm-slim AS final
ENV TZ=Europe/Berlin
ENV DATA_PATH=/data
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_HTTP_PORTS=8080
WORKDIR /app
EXPOSE 8080
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends bash curl lsb-release wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    mkdir -p /data && \
    chown -R app:app /data
COPY --from=build /app/publish/ .
RUN chown -R app:app /app
USER $APP_UID
ENTRYPOINT ["/app/MTWireGuard"]