name: CI

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tag:
        required: true
        description: 'Output image tag'
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        env:
          IMAGE_NAME: "techgarageir/mtwireguard" 
          GHCR_IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/mtwireguard"
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: >
            ${{
              github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
              ? format('{0}:{1}, {0}:latest, {2}:{1}, {2}:latest', env.IMAGE_NAME, github.ref_name, env.GHCR_IMAGE_NAME)
              : format('{0}:{1}, {2}:{1}', env.IMAGE_NAME, inputs.tag, env.GHCR_IMAGE_NAME)
            }}
