name: CI

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set Runtime Identifier
        id: set_rid
        run: |
          if [[ "$RUNNER_ARCH" == "X64" ]]; then echo "linux-x64" >> $GITHUB_ENV; else echo "linux-arm64" >> $GITHUB_ENV; fi

      - name: Restore Dependencies
        run: dotnet restore --runtime ${{ env.RID }}

      - name: Build and Publish
        run: dotnet publish ./UI/MTWireGuard.csproj -c Release -o publish --runtime ${{ env.RID }} --no-restore --self-contained true

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        env:
          TAG_NAME: ${{ github.ref_name }}
          IMAGE_NAME: "techgarageir/mtwireguard" 
          GHCR_IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/mtwireguard"
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            techgarageir/mtwireguard:test
            ghcr.io/${{ github.repository_owner }}/mtwireguard:test
